export default [
    {
        login: 'brupm',
        id: 336,
        node_id: 'MDQ6VXNlcjMzNg==',
        avatar_url: 'https://avatars.githubusercontent.com/u/336?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/brupm',
        html_url: 'https://github.com/brupm',
        followers_url: 'https://api.github.com/users/brupm/followers',
        following_url:
            'https://api.github.com/users/brupm/following{/other_user}',
        gists_url: 'https://api.github.com/users/brupm/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/brupm/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/brupm/subscriptions',
        organizations_url: 'https://api.github.com/users/brupm/orgs',
        repos_url: 'https://api.github.com/users/brupm/repos',
        events_url: 'https://api.github.com/users/brupm/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/brupm/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'dusty',
        id: 792,
        node_id: 'MDQ6VXNlcjc5Mg==',
        avatar_url: 'https://avatars.githubusercontent.com/u/792?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/dusty',
        html_url: 'https://github.com/dusty',
        followers_url: 'https://api.github.com/users/dusty/followers',
        following_url:
            'https://api.github.com/users/dusty/following{/other_user}',
        gists_url: 'https://api.github.com/users/dusty/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/dusty/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/dusty/subscriptions',
        organizations_url: 'https://api.github.com/users/dusty/orgs',
        repos_url: 'https://api.github.com/users/dusty/repos',
        events_url: 'https://api.github.com/users/dusty/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/dusty/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'dennisreimann',
        id: 886,
        node_id: 'MDQ6VXNlcjg4Ng==',
        avatar_url: 'https://avatars.githubusercontent.com/u/886?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/dennisreimann',
        html_url: 'https://github.com/dennisreimann',
        followers_url: 'https://api.github.com/users/dennisreimann/followers',
        following_url:
            'https://api.github.com/users/dennisreimann/following{/other_user}',
        gists_url: 'https://api.github.com/users/dennisreimann/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/dennisreimann/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/dennisreimann/subscriptions',
        organizations_url: 'https://api.github.com/users/dennisreimann/orgs',
        repos_url: 'https://api.github.com/users/dennisreimann/repos',
        events_url:
            'https://api.github.com/users/dennisreimann/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/dennisreimann/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'amiroff',
        id: 919,
        node_id: 'MDQ6VXNlcjkxOQ==',
        avatar_url: 'https://avatars.githubusercontent.com/u/919?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/amiroff',
        html_url: 'https://github.com/amiroff',
        followers_url: 'https://api.github.com/users/amiroff/followers',
        following_url:
            'https://api.github.com/users/amiroff/following{/other_user}',
        gists_url: 'https://api.github.com/users/amiroff/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/amiroff/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/amiroff/subscriptions',
        organizations_url: 'https://api.github.com/users/amiroff/orgs',
        repos_url: 'https://api.github.com/users/amiroff/repos',
        events_url: 'https://api.github.com/users/amiroff/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/amiroff/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'sunfmin',
        id: 1014,
        node_id: 'MDQ6VXNlcjEwMTQ=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1014?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/sunfmin',
        html_url: 'https://github.com/sunfmin',
        followers_url: 'https://api.github.com/users/sunfmin/followers',
        following_url:
            'https://api.github.com/users/sunfmin/following{/other_user}',
        gists_url: 'https://api.github.com/users/sunfmin/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/sunfmin/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/sunfmin/subscriptions',
        organizations_url: 'https://api.github.com/users/sunfmin/orgs',
        repos_url: 'https://api.github.com/users/sunfmin/repos',
        events_url: 'https://api.github.com/users/sunfmin/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/sunfmin/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'holin',
        id: 1019,
        node_id: 'MDQ6VXNlcjEwMTk=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1019?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/holin',
        html_url: 'https://github.com/holin',
        followers_url: 'https://api.github.com/users/holin/followers',
        following_url:
            'https://api.github.com/users/holin/following{/other_user}',
        gists_url: 'https://api.github.com/users/holin/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/holin/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/holin/subscriptions',
        organizations_url: 'https://api.github.com/users/holin/orgs',
        repos_url: 'https://api.github.com/users/holin/repos',
        events_url: 'https://api.github.com/users/holin/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/holin/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'andrew',
        id: 1060,
        node_id: 'MDQ6VXNlcjEwNjA=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1060?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/andrew',
        html_url: 'https://github.com/andrew',
        followers_url: 'https://api.github.com/users/andrew/followers',
        following_url:
            'https://api.github.com/users/andrew/following{/other_user}',
        gists_url: 'https://api.github.com/users/andrew/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/andrew/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/andrew/subscriptions',
        organizations_url: 'https://api.github.com/users/andrew/orgs',
        repos_url: 'https://api.github.com/users/andrew/repos',
        events_url: 'https://api.github.com/users/andrew/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/andrew/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'maxterry',
        id: 1083,
        node_id: 'MDQ6VXNlcjEwODM=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1083?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/maxterry',
        html_url: 'https://github.com/maxterry',
        followers_url: 'https://api.github.com/users/maxterry/followers',
        following_url:
            'https://api.github.com/users/maxterry/following{/other_user}',
        gists_url: 'https://api.github.com/users/maxterry/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/maxterry/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/maxterry/subscriptions',
        organizations_url: 'https://api.github.com/users/maxterry/orgs',
        repos_url: 'https://api.github.com/users/maxterry/repos',
        events_url: 'https://api.github.com/users/maxterry/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/maxterry/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'charlenopires',
        id: 1365,
        node_id: 'MDQ6VXNlcjEzNjU=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1365?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/charlenopires',
        html_url: 'https://github.com/charlenopires',
        followers_url: 'https://api.github.com/users/charlenopires/followers',
        following_url:
            'https://api.github.com/users/charlenopires/following{/other_user}',
        gists_url: 'https://api.github.com/users/charlenopires/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/charlenopires/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/charlenopires/subscriptions',
        organizations_url: 'https://api.github.com/users/charlenopires/orgs',
        repos_url: 'https://api.github.com/users/charlenopires/repos',
        events_url:
            'https://api.github.com/users/charlenopires/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/charlenopires/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'techthumb',
        id: 1367,
        node_id: 'MDQ6VXNlcjEzNjc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1367?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/techthumb',
        html_url: 'https://github.com/techthumb',
        followers_url: 'https://api.github.com/users/techthumb/followers',
        following_url:
            'https://api.github.com/users/techthumb/following{/other_user}',
        gists_url: 'https://api.github.com/users/techthumb/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/techthumb/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/techthumb/subscriptions',
        organizations_url: 'https://api.github.com/users/techthumb/orgs',
        repos_url: 'https://api.github.com/users/techthumb/repos',
        events_url: 'https://api.github.com/users/techthumb/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/techthumb/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'rmoriz',
        id: 1527,
        node_id: 'MDQ6VXNlcjE1Mjc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1527?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rmoriz',
        html_url: 'https://github.com/rmoriz',
        followers_url: 'https://api.github.com/users/rmoriz/followers',
        following_url:
            'https://api.github.com/users/rmoriz/following{/other_user}',
        gists_url: 'https://api.github.com/users/rmoriz/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/rmoriz/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rmoriz/subscriptions',
        organizations_url: 'https://api.github.com/users/rmoriz/orgs',
        repos_url: 'https://api.github.com/users/rmoriz/repos',
        events_url: 'https://api.github.com/users/rmoriz/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/rmoriz/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'lgs',
        id: 1573,
        node_id: 'MDQ6VXNlcjE1NzM=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1573?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/lgs',
        html_url: 'https://github.com/lgs',
        followers_url: 'https://api.github.com/users/lgs/followers',
        following_url:
            'https://api.github.com/users/lgs/following{/other_user}',
        gists_url: 'https://api.github.com/users/lgs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/lgs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/lgs/subscriptions',
        organizations_url: 'https://api.github.com/users/lgs/orgs',
        repos_url: 'https://api.github.com/users/lgs/repos',
        events_url: 'https://api.github.com/users/lgs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/lgs/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'tambet',
        id: 1631,
        node_id: 'MDQ6VXNlcjE2MzE=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/tambet',
        html_url: 'https://github.com/tambet',
        followers_url: 'https://api.github.com/users/tambet/followers',
        following_url:
            'https://api.github.com/users/tambet/following{/other_user}',
        gists_url: 'https://api.github.com/users/tambet/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/tambet/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/tambet/subscriptions',
        organizations_url: 'https://api.github.com/users/tambet/orgs',
        repos_url: 'https://api.github.com/users/tambet/repos',
        events_url: 'https://api.github.com/users/tambet/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/tambet/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'mikehodgson',
        id: 2416,
        node_id: 'MDQ6VXNlcjI0MTY=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2416?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/mikehodgson',
        html_url: 'https://github.com/mikehodgson',
        followers_url: 'https://api.github.com/users/mikehodgson/followers',
        following_url:
            'https://api.github.com/users/mikehodgson/following{/other_user}',
        gists_url: 'https://api.github.com/users/mikehodgson/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/mikehodgson/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/mikehodgson/subscriptions',
        organizations_url: 'https://api.github.com/users/mikehodgson/orgs',
        repos_url: 'https://api.github.com/users/mikehodgson/repos',
        events_url: 'https://api.github.com/users/mikehodgson/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/mikehodgson/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'dingyi',
        id: 2486,
        node_id: 'MDQ6VXNlcjI0ODY=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2486?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/dingyi',
        html_url: 'https://github.com/dingyi',
        followers_url: 'https://api.github.com/users/dingyi/followers',
        following_url:
            'https://api.github.com/users/dingyi/following{/other_user}',
        gists_url: 'https://api.github.com/users/dingyi/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/dingyi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/dingyi/subscriptions',
        organizations_url: 'https://api.github.com/users/dingyi/orgs',
        repos_url: 'https://api.github.com/users/dingyi/repos',
        events_url: 'https://api.github.com/users/dingyi/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/dingyi/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'Gregg',
        id: 2618,
        node_id: 'MDQ6VXNlcjI2MTg=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2618?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Gregg',
        html_url: 'https://github.com/Gregg',
        followers_url: 'https://api.github.com/users/Gregg/followers',
        following_url:
            'https://api.github.com/users/Gregg/following{/other_user}',
        gists_url: 'https://api.github.com/users/Gregg/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/Gregg/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Gregg/subscriptions',
        organizations_url: 'https://api.github.com/users/Gregg/orgs',
        repos_url: 'https://api.github.com/users/Gregg/repos',
        events_url: 'https://api.github.com/users/Gregg/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/Gregg/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'yangjindong',
        id: 2887,
        node_id: 'MDQ6VXNlcjI4ODc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2887?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/yangjindong',
        html_url: 'https://github.com/yangjindong',
        followers_url: 'https://api.github.com/users/yangjindong/followers',
        following_url:
            'https://api.github.com/users/yangjindong/following{/other_user}',
        gists_url: 'https://api.github.com/users/yangjindong/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/yangjindong/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/yangjindong/subscriptions',
        organizations_url: 'https://api.github.com/users/yangjindong/orgs',
        repos_url: 'https://api.github.com/users/yangjindong/repos',
        events_url: 'https://api.github.com/users/yangjindong/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/yangjindong/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'tpaksu',
        id: 3295,
        node_id: 'MDQ6VXNlcjMyOTU=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3295?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/tpaksu',
        html_url: 'https://github.com/tpaksu',
        followers_url: 'https://api.github.com/users/tpaksu/followers',
        following_url:
            'https://api.github.com/users/tpaksu/following{/other_user}',
        gists_url: 'https://api.github.com/users/tpaksu/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/tpaksu/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/tpaksu/subscriptions',
        organizations_url: 'https://api.github.com/users/tpaksu/orgs',
        repos_url: 'https://api.github.com/users/tpaksu/repos',
        events_url: 'https://api.github.com/users/tpaksu/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/tpaksu/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'abraham',
        id: 3341,
        node_id: 'MDQ6VXNlcjMzNDE=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3341?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/abraham',
        html_url: 'https://github.com/abraham',
        followers_url: 'https://api.github.com/users/abraham/followers',
        following_url:
            'https://api.github.com/users/abraham/following{/other_user}',
        gists_url: 'https://api.github.com/users/abraham/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/abraham/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/abraham/subscriptions',
        organizations_url: 'https://api.github.com/users/abraham/orgs',
        repos_url: 'https://api.github.com/users/abraham/repos',
        events_url: 'https://api.github.com/users/abraham/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/abraham/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'fabricio',
        id: 3382,
        node_id: 'MDQ6VXNlcjMzODI=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3382?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/fabricio',
        html_url: 'https://github.com/fabricio',
        followers_url: 'https://api.github.com/users/fabricio/followers',
        following_url:
            'https://api.github.com/users/fabricio/following{/other_user}',
        gists_url: 'https://api.github.com/users/fabricio/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/fabricio/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/fabricio/subscriptions',
        organizations_url: 'https://api.github.com/users/fabricio/orgs',
        repos_url: 'https://api.github.com/users/fabricio/repos',
        events_url: 'https://api.github.com/users/fabricio/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/fabricio/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'jnarowski',
        id: 3435,
        node_id: 'MDQ6VXNlcjM0MzU=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3435?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/jnarowski',
        html_url: 'https://github.com/jnarowski',
        followers_url: 'https://api.github.com/users/jnarowski/followers',
        following_url:
            'https://api.github.com/users/jnarowski/following{/other_user}',
        gists_url: 'https://api.github.com/users/jnarowski/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/jnarowski/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/jnarowski/subscriptions',
        organizations_url: 'https://api.github.com/users/jnarowski/orgs',
        repos_url: 'https://api.github.com/users/jnarowski/repos',
        events_url: 'https://api.github.com/users/jnarowski/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/jnarowski/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'ledermann',
        id: 3557,
        node_id: 'MDQ6VXNlcjM1NTc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3557?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/ledermann',
        html_url: 'https://github.com/ledermann',
        followers_url: 'https://api.github.com/users/ledermann/followers',
        following_url:
            'https://api.github.com/users/ledermann/following{/other_user}',
        gists_url: 'https://api.github.com/users/ledermann/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/ledermann/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/ledermann/subscriptions',
        organizations_url: 'https://api.github.com/users/ledermann/orgs',
        repos_url: 'https://api.github.com/users/ledermann/repos',
        events_url: 'https://api.github.com/users/ledermann/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/ledermann/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'brainv',
        id: 3684,
        node_id: 'MDQ6VXNlcjM2ODQ=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3684?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/brainv',
        html_url: 'https://github.com/brainv',
        followers_url: 'https://api.github.com/users/brainv/followers',
        following_url:
            'https://api.github.com/users/brainv/following{/other_user}',
        gists_url: 'https://api.github.com/users/brainv/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/brainv/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/brainv/subscriptions',
        organizations_url: 'https://api.github.com/users/brainv/orgs',
        repos_url: 'https://api.github.com/users/brainv/repos',
        events_url: 'https://api.github.com/users/brainv/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/brainv/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'mrluanma',
        id: 3856,
        node_id: 'MDQ6VXNlcjM4NTY=',
        avatar_url: 'https://avatars.githubusercontent.com/u/3856?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/mrluanma',
        html_url: 'https://github.com/mrluanma',
        followers_url: 'https://api.github.com/users/mrluanma/followers',
        following_url:
            'https://api.github.com/users/mrluanma/following{/other_user}',
        gists_url: 'https://api.github.com/users/mrluanma/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/mrluanma/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/mrluanma/subscriptions',
        organizations_url: 'https://api.github.com/users/mrluanma/orgs',
        repos_url: 'https://api.github.com/users/mrluanma/repos',
        events_url: 'https://api.github.com/users/mrluanma/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/mrluanma/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'heijmerikx',
        id: 4012,
        node_id: 'MDQ6VXNlcjQwMTI=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4012?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/heijmerikx',
        html_url: 'https://github.com/heijmerikx',
        followers_url: 'https://api.github.com/users/heijmerikx/followers',
        following_url:
            'https://api.github.com/users/heijmerikx/following{/other_user}',
        gists_url: 'https://api.github.com/users/heijmerikx/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/heijmerikx/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/heijmerikx/subscriptions',
        organizations_url: 'https://api.github.com/users/heijmerikx/orgs',
        repos_url: 'https://api.github.com/users/heijmerikx/repos',
        events_url: 'https://api.github.com/users/heijmerikx/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/heijmerikx/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'DougHall',
        id: 4019,
        node_id: 'MDQ6VXNlcjQwMTk=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4019?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/DougHall',
        html_url: 'https://github.com/DougHall',
        followers_url: 'https://api.github.com/users/DougHall/followers',
        following_url:
            'https://api.github.com/users/DougHall/following{/other_user}',
        gists_url: 'https://api.github.com/users/DougHall/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/DougHall/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/DougHall/subscriptions',
        organizations_url: 'https://api.github.com/users/DougHall/orgs',
        repos_url: 'https://api.github.com/users/DougHall/repos',
        events_url: 'https://api.github.com/users/DougHall/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/DougHall/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'kaichen',
        id: 4048,
        node_id: 'MDQ6VXNlcjQwNDg=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4048?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/kaichen',
        html_url: 'https://github.com/kaichen',
        followers_url: 'https://api.github.com/users/kaichen/followers',
        following_url:
            'https://api.github.com/users/kaichen/following{/other_user}',
        gists_url: 'https://api.github.com/users/kaichen/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/kaichen/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/kaichen/subscriptions',
        organizations_url: 'https://api.github.com/users/kaichen/orgs',
        repos_url: 'https://api.github.com/users/kaichen/repos',
        events_url: 'https://api.github.com/users/kaichen/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/kaichen/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'benatkin',
        id: 4126,
        node_id: 'MDQ6VXNlcjQxMjY=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4126?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/benatkin',
        html_url: 'https://github.com/benatkin',
        followers_url: 'https://api.github.com/users/benatkin/followers',
        following_url:
            'https://api.github.com/users/benatkin/following{/other_user}',
        gists_url: 'https://api.github.com/users/benatkin/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/benatkin/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/benatkin/subscriptions',
        organizations_url: 'https://api.github.com/users/benatkin/orgs',
        repos_url: 'https://api.github.com/users/benatkin/repos',
        events_url: 'https://api.github.com/users/benatkin/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/benatkin/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'wuwx',
        id: 4401,
        node_id: 'MDQ6VXNlcjQ0MDE=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4401?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/wuwx',
        html_url: 'https://github.com/wuwx',
        followers_url: 'https://api.github.com/users/wuwx/followers',
        following_url:
            'https://api.github.com/users/wuwx/following{/other_user}',
        gists_url: 'https://api.github.com/users/wuwx/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/wuwx/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/wuwx/subscriptions',
        organizations_url: 'https://api.github.com/users/wuwx/orgs',
        repos_url: 'https://api.github.com/users/wuwx/repos',
        events_url: 'https://api.github.com/users/wuwx/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/wuwx/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'ihower',
        id: 4557,
        node_id: 'MDQ6VXNlcjQ1NTc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4557?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/ihower',
        html_url: 'https://github.com/ihower',
        followers_url: 'https://api.github.com/users/ihower/followers',
        following_url:
            'https://api.github.com/users/ihower/following{/other_user}',
        gists_url: 'https://api.github.com/users/ihower/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/ihower/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ihower/subscriptions',
        organizations_url: 'https://api.github.com/users/ihower/orgs',
        repos_url: 'https://api.github.com/users/ihower/repos',
        events_url: 'https://api.github.com/users/ihower/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/ihower/received_events',
        type: 'User',
        site_admin: false,
    },
]
