export default {
    login: 'EvanYou',
    id: 3600653,
    node_id: 'MDQ6VXNlcjM2MDA2NTM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3600653?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/EvanYou',
    html_url: 'https://github.com/EvanYou',
    followers_url: 'https://api.github.com/users/EvanYou/followers',
    following_url:
        'https://api.github.com/users/EvanYou/following{/other_user}',
    gists_url: 'https://api.github.com/users/EvanYou/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/EvanYou/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/EvanYou/subscriptions',
    organizations_url: 'https://api.github.com/users/EvanYou/orgs',
    repos_url: 'https://api.github.com/users/EvanYou/repos',
    events_url: 'https://api.github.com/users/EvanYou/events{/privacy}',
    received_events_url: 'https://api.github.com/users/EvanYou/received_events',
    type: 'User',
    site_admin: false,
    name: 'EvanYou',
    company: null,
    blog: '',
    location: 'Chongqing',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 5,
    public_gists: 0,
    followers: 20,
    following: 2,
    created_at: '2013-02-15T08:08:14Z',
    updated_at: '2021-07-22T22:00:38Z',
}
