export default {
    login: 'yyx990803',
    id: 499550,
    node_id: 'MDQ6VXNlcjQ5OTU1MA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/499550?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/yyx990803',
    html_url: 'https://github.com/yyx990803',
    followers_url: 'https://api.github.com/users/yyx990803/followers',
    following_url:
        'https://api.github.com/users/yyx990803/following{/other_user}',
    gists_url: 'https://api.github.com/users/yyx990803/gists{/gist_id}',
    starred_url:
        'https://api.github.com/users/yyx990803/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/yyx990803/subscriptions',
    organizations_url: 'https://api.github.com/users/yyx990803/orgs',
    repos_url: 'https://api.github.com/users/yyx990803/repos',
    events_url: 'https://api.github.com/users/yyx990803/events{/privacy}',
    received_events_url:
        'https://api.github.com/users/yyx990803/received_events',
    type: 'User',
    site_admin: false,
    name: 'Evan You',
    company: 'vuejs',
    blog: 'http://evanyou.me',
    location: 'New Jersey ⇄ China',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 179,
    public_gists: 69,
    followers: 75606,
    following: 94,
    created_at: '2010-11-28T01:05:40Z',
    updated_at: '2021-11-04T13:21:47Z',
}
